apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
spec:
  replicas: 1
  selector:
    matchLabels:
      component: file-service
  template:
    metadata:
      labels:
        component: file-service
    spec:
      containers:
        - name: file-service
          image: {{.Values.image}}
          ports:
            - containerPort: {{.Values.port}}
          env:
            - name: PORT
              value: "{{.Values.port}}"
            - name: ENDPOINT_PREFIX
              value: "{{.Values.endpointPrefix}}"
            - name: MINIO_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: accesskey
            - name: MINIO_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secretkey
            - name: MINIO_USE_SSL
              value: "false"
