apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: file-service
  # annotations:
  # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: {{.Values.endpointPrefix}}
            pathType: Prefix
            backend:
              service:
                name: file-service
                port:
                  number: {{.Values.port}}
